DROP DATABASE IF EXISTS shops_db;
CREATE DATABASE shops_db;
\c shops_db

DROP TABLE IF EXISTS users;

CREATE TABLE users
(id BIGSERIAL PRIMARY KEY,
first_name VARCHAR(255),
last_name VARCHAR(255),
email VARCHAR(255),
password VARCHAR(255));
